FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./scripts/osm2es.py /usr/src/app/scripts/osm2es.py

CMD [ "python", "/usr/src/app/scripts/osm2es.py" ]

