version: "3.7"
services:
  download:
    # set the UID and GID in the .env file respectively
    # by running "id -u" and "id -g" to 
    user: $UID:$GID
    image: openmaptiles/openmaptiles-tools
    container_name: openmaptiles-tools
    volumes:
      - ./data:/tileset
    networks: 
      - osm2es
    command: "bash -c \"mkdir -p /tileset/${TASK_NAME}; download-osm ${DOWNLOAD_TYPE} ${DOWNLOAD_AREA} -o /tileset/${TASK_NAME}/data.pbf --force\""
  upload:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile-upload
    container_name: upload
    environment:
      - TASK_NAME=${TASK_NAME}
      - DOWNLOAD_AREA=${DOWNLOAD_AREA}
      - OSM_CONFIG_FILE=/app/osmconf.ini
      - ES_URL=${ES_URL}
      - ES_INDEX_PREFFIX=${ES_INDEX_PREFFIX}
      - ES_REPLICAS=${ES_REPLICAS}
    volumes:
      - .:/app
    command: "/app/scripts/upload.sh"
  osmium:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile-osmium
    container_name: osmium
    env_file:
      - .env
    volumes:
      - ./scripts:/usr/src/app/scripts
      - ./data:/usr/src/app/data

networks:
  osm2es:
